repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: detect-private-key
        exclude: '.env|.env.example'

  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black
        language_version: python3.11
        args: ['--line-length=120']

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: ['--max-line-length=120', '--extend-ignore=E203,W503']
        exclude: 'tests/|memory-bank/'

  - repo: local
    hooks:
      - id: check-requirements
        name: Check requirements.txt
        entry: python -c "import pkg_resources; pkg_resources.require(open('requirements.txt').read().splitlines())"
        language: system
        files: requirements.txt
        pass_filenames: false

      - id: validate-deployment
        name: Validate Railway deployment files
        entry: bash -c 'test -f railway.json && test -f nixpacks.toml && test -f Procfile'
        language: system
        pass_filenames: false

      - id: run-unit-tests
        name: Run critical unit tests
        entry: python -m pytest tests/unit/test_core_app.py -v --tb=short
        language: system
        pass_filenames: false
        stages: [commit]