[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "gcc", "nodejs", "nodePackages.npm"]

[phases.install]
cmds = [
  "pip install --break-system-packages -r requirements.txt",
  "cd dashboard && npm install",
  "cd dashboard && npm run build"
]

[start]
cmd = "python main_enhanced.py"
