[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "pip install --break-system-packages -r requirements_direct.txt",
  "echo 'Production API build completed'",
  "ls -la direct_credit_api_with_phone.py"
]

[start]
cmd = "python direct_credit_api_with_phone.py"
