[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "pip install --break-system-packages -r requirements.txt",
  "echo 'Production LLM Orchestration API build completed'",
  "ls -la main_minimal.py main_enhanced.py"
]

[start]
cmd = "python -m uvicorn main_minimal:app --host 0.0.0.0 --port $PORT"
