# Railway Configuration for Open WebUI Production Deployment
# This deploys Open WebUI as a separate Railway service using the official Docker image

[build]
builder = "DOCKER"

[deploy]
dockerfilePath = "Dockerfile.openwebui"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
# Connect to production Tilores API
OPENAI_API_BASE_URL = "https://tilores-x.up.railway.app"
OPENAI_API_KEY = "dummy"

# Authentication and Security
WEBUI_AUTH = "true"
WEBUI_SECRET_KEY = "your-secret-key-here"

# Team Evaluation Features
ENABLE_COMMUNITY_SHARING = "true"
ENABLE_MESSAGE_RATING = "true"
ENABLE_MODEL_FILTER = "true"
ENABLE_EVALUATION_ARENA = "true"
ENABLE_ADMIN_EXPORT = "true"
ENABLE_ADMIN_CHAT_ACCESS = "true"

# Model Configuration
TASK_MODEL = "gpt-4o-mini"
TITLE_GENERATION_PROMPT_TEMPLATE = "Generate a concise title for this conversation"

# Webhook Integration
WEBHOOK_URL = "https://tilores-x.up.railway.app/webhooks/openwebui-rating"

# Production Optimizations
DATA_DIR = "/app/backend/data"
ENABLE_SIGNUP = "false"  # Only admin can create accounts
DEFAULT_USER_ROLE = "user"
