#!/bin/bash

# Import Tilores Models to Open WebUI
# This script configures all 9 Tilores models in Open WebUI

echo "🚀 Importing Tilores Models to Open WebUI"
echo "========================================"

OPENWEBUI_URL="https://tilores-x-ui.up.railway.app"
TILORES_API_URL="https://tilores-x.up.railway.app"

echo "📋 Open WebUI URL: $OPENWEBUI_URL"
echo "🔗 Tilores API URL: $TILORES_API_URL"
echo ""

echo "📝 Manual Configuration Steps:"
echo ""
echo "1. 🌐 Open your browser and go to:"
echo "   $OPENWEBUI_URL"
echo ""
echo "2. 👤 Create/Login to your admin account"
echo ""
echo "3. ⚙️ Go to Settings → Connections"
echo ""
echo "4. 🔗 Add OpenAI Connection:"
echo "   • Name: Tilores API"
echo "   • Base URL: $TILORES_API_URL"
echo "   • API Key: dummy"
echo "   • Click 'Verify Connection'"
echo ""
echo "5. ✅ You should see 9 models discovered:"
echo "   📊 OpenAI Models (3):"
echo "   • gpt-4o"
echo "   • gpt-4o-mini"
echo "   • gpt-3.5-turbo"
echo ""
echo "   🧠 Google Gemini Models (4):"
echo "   • gemini-1.5-flash"
echo "   • gemini-1.5-pro"
echo "   • gemini-2.0-flash-exp"
echo "   • gemini-2.5-flash"
echo ""
echo "   ⚡ Groq Models (2):"
echo "   • llama-3.3-70b-versatile"
echo "   • deepseek-r1-distill-llama-70b"
echo ""
echo "6. 🎯 Test a model by starting a new chat"
echo ""
echo "🎉 All models will be available for your team to use!"
echo ""
echo "📋 Model Recommendations:"
echo "• 🚀 Fast responses: gpt-4o-mini, gemini-1.5-flash"
echo "• 🧠 Complex analysis: gpt-4o, gemini-1.5-pro"
echo "• 💰 Cost-effective: gpt-3.5-turbo, llama-3.3-70b-versatile"
echo "• 🔬 Experimental: gemini-2.0-flash-exp, deepseek-r1-distill-llama-70b"
