name: Minimal Deploy Check

on:
  push:
    branches: [ main ]

jobs:
  quick-validation:
    name: Quick Validation
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Quick syntax validation
        run: |
          python -c "
          # Test Python syntax of core files without importing complex dependencies
          import sys
          import ast

          print('🧪 Testing Python syntax of core architecture files...')

          # Test agent_prompts.py syntax
          try:
              with open('agent_prompts.py', 'r') as f:
                  ast.parse(f.read())
              print('✅ agent_prompts.py syntax valid')
          except Exception as e:
              print(f'❌ agent_prompts.py syntax error: {e}')
              sys.exit(1)

          # Test main_enhanced.py syntax (just check if it parses)
          try:
              with open('main_enhanced.py', 'r') as f:
                  ast.parse(f.read())
              print('✅ main_enhanced.py syntax valid')
          except Exception as e:
              print(f'❌ main_enhanced.py syntax error: {e}')
              sys.exit(1)

          # Test direct_credit_api_fixed.py syntax
          try:
              with open('direct_credit_api_fixed.py', 'r') as f:
                  ast.parse(f.read())
              print('✅ direct_credit_api_fixed.py syntax valid')
          except Exception as e:
              print(f'❌ direct_credit_api_fixed.py syntax error: {e}')
              sys.exit(1)

          print('✅ All core Python files have valid syntax - Railway deployment ready')
          "
