name: Minimal Deploy Check

on:
  push:
    branches: [ main ]

jobs:
  quick-validation:
    name: Quick Validation
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Quick import test
        run: |
          pip install -r requirements.txt
          python -c "
          import os
          # Set dummy env vars for import test if not present
          if not os.getenv('TILORES_API_URL'):
              os.environ['TILORES_API_URL'] = 'https://dummy.tilores.api'
          if not os.getenv('TILORES_CLIENT_ID'):
              os.environ['TILORES_CLIENT_ID'] = 'dummy_client_id'
          if not os.getenv('TILORES_CLIENT_SECRET'):
              os.environ['TILORES_CLIENT_SECRET'] = 'dummy_secret'
          if not os.getenv('TILORES_TOKEN_URL'):
              os.environ['TILORES_TOKEN_URL'] = 'https://dummy.token.url'
          if not os.getenv('OPENAI_API_KEY'):
              os.environ['OPENAI_API_KEY'] = 'dummy_openai_key'

          from agent_prompts import AGENT_PROMPTS
          print('✅ Agent prompts loaded successfully')

          # Test MultiProviderCreditAPI import (may fail without real credentials)
          try:
              from direct_credit_api_fixed import MultiProviderCreditAPI
              print('✅ MultiProviderCreditAPI import successful')
          except Exception as e:
              print(f'⚠️ MultiProviderCreditAPI import failed (expected without real credentials): {e}')

          # Test FastAPI app import
          from main_enhanced import app
          print('✅ FastAPI app import successful')

          print('✅ New LLM Orchestration Architecture imports successful - Railway will auto-deploy')
          "
