name: Minimal Deploy Check

on:
  push:
    branches: [ main ]

jobs:
  quick-validation:
    name: Quick Validation
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Quick import test
        run: |
          pip install fastapi uvicorn
          python -c "
          # Test only core imports that don't require external dependencies
          import sys
          import os

          print('🧪 Testing core imports...')

          try:
              from agent_prompts import AGENT_PROMPTS
              print('✅ Agent prompts loaded successfully')
          except Exception as e:
              print(f'❌ Agent prompts import failed: {e}')
              sys.exit(1)

          try:
              from main_enhanced import app
              print('✅ FastAPI app import successful')
          except Exception as e:
              print(f'❌ FastAPI app import failed: {e}')
              sys.exit(1)

          print('✅ Core architecture imports successful - Railway deployment ready')
          "
