name: Minimal Deploy Check

on:
  push:
    branches: [ main ]

jobs:
  quick-validation:
    name: Quick Validation
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Quick import test
        run: |
          pip install -r requirements.txt
          python -c "
          from direct_credit_api_fixed import MultiProviderCreditAPI
          from agent_prompts import AGENT_PROMPTS
          from main_enhanced import app
          print('✅ New LLM Orchestration Architecture imports successful - Railway will auto-deploy')
          "
