name: Minimal Deploy Check

on:
  push:
    branches: [ main ]

jobs:
  quick-validation:
    name: Quick Validation
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Quick import test
        run: |
          pip install pydantic
          python -c "
          # Test only the most basic imports that define our architecture
          import sys

          print('🧪 Testing basic architecture imports...')

          try:
              from agent_prompts import AGENT_PROMPTS
              print('✅ Agent prompts loaded successfully')
              print(f'   📊 Found {len(AGENT_PROMPTS)} agents defined')
          except Exception as e:
              print(f'❌ Agent prompts import failed: {e}')
              sys.exit(1)

          try:
              # Just import the models, not the full app
              from main_enhanced import ChatCompletionRequest, ChatCompletionResponse
              print('✅ FastAPI models import successful')
          except Exception as e:
              print(f'❌ FastAPI models import failed: {e}')
              sys.exit(1)

          print('✅ Core architecture validation successful - Railway deployment ready')
          "
